In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
### 1

A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])

U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [3]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [4]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [5]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [6]:
### 2a

norm_e = D[0][0]
print(f'Евклидова норма:\n{norm_e}')

# numpy: 
print(np.linalg.norm(A, ord=2))

Евклидова норма:
8.824868854820442
8.824868854820444


In [7]:
### 2б

norm_f = np.sqrt(sum(D[i][i]**2 for i in range(np.linalg.matrix_rank(A))))
print(f'Норма Фробениуса:\n{norm_f}')

# numpy:
print(np.linalg.norm(A, ord='fro'))

Норма Фробениуса:
11.045361017187261
11.045361017187261
